### ISSUE TITLE
Login Action is logging in as `undefined`

### ISSUE THREAD

**Issue by anarian** [atlassian/gajira#12]
I'm trying to set up actions to transition tickets when pull requests are opened/closed, but using the `atlassian/gajira-login` action is logging me in as `undefined`, causing the other actions to fail.

![image](https://user-images.githubusercontent.com/4705059/130653951-5576e2ed-08ff-4ca5-93cf-904001a920a3.png)

This is my current actions definition:
```
name: Transition ticket for PRs

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Ticket Transition
    steps:
    - name: Login
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Find ticket IDs in commit messages
      uses: atlassian/gajira-find-issue-key@v2.0.2
      id: ticketids
      with:
        from: commits
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Transition to "In Code Review"
      id: transition-incodereview
      if: ${{ github.event.pull_request.action == 'opened' }}
      uses: atlassian/gajira-transition@v2.0.2
      with:
        issue: ${{ steps.ticketids.outputs.issue }}
        transition: "In Code Review"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Transition to "Ready to Deploy"
      id: transition-readytodeploy
      if: ${{ github.event.pull_request.action == 'closed' && github.event.pull_request.merged == true }}
      uses: atlassian/gajira-transition@v2.0.2
      with:
        issue: ${{ steps.ticketids.outputs.issue }}
        transition: "Ready to Deploy"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
