### ISSUE TITLE
Login action does not log in the go-jira CLI

### ISSUE THREAD

**Issue by chrisinajar** [atlassian/gajira#9]
The Login action should setup the go-jira cli to be authenticated using the same information it was passed so that you don't need to do it yourself.

basically, this should work:
```
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Setup CLI tool
        uses: atlassian/gajira-cli@master
        with:
          version: 1.0.27

      - name: Check ticket state
        run: |
          jira view ENG-1234
```
but instead it stalls out asking for a token
